# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "What tag to use"
        default: "1.0.0"      
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        persist-credentials: true

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.4' # The Go version to download (if necessary) and use.

    - name: Install golint
      run: |
        go get golang.org/x/lint/golint
        go install golang.org/x/lint/golint

    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...

    - name: Run testing
      run: go test -v ./...

    - name: Run build
      run: |
        mkdir -p /tmp/release/
      
        GOOS=linux GOARCH=amd64 go build -o duptfy cmd/duptfy/main.go
        tar -cf /tmp/release/duptfy-linux-amd64.tar duptfy

        GOOS=linux GOARCH=arm go build -o duptfy cmd/duptfy/main.go
        tar -cf /tmp/release/duptfy-linux-arm.tar duptfy

    - name: "Configure tags"
      if: github.ref_name == 'main'
      run: |
        #Get latest tags
        git ls-remote --tags --sort=committerdate | grep -o 'v.*' | sort -r
        #Create Tag
        git tag ${{ github.event.inputs.tag }}
        #Push tag
        git push origin ${{ github.event.inputs.tag }}

    - name: Release
      if: github.ref_name == 'main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: /tmp/release/*
